version: '3.1'
services:
  postgres:
    restart: always
    ports:
      - '5432:5432'
    image: 'postgres:latest'
    volumes:
      - db-data2:/var/lib/postgresql/data
    secrets:
      - psql_user
      - psql_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
      POSTGRES_USER_FILE: /run/secrets/psql_user
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            database: postgres
            user: postgres
            password: postgres_password_123
            rawAccess: true
            port: '5432'
            migrations: true
volumes:
  db-data2:
secrets:
  psql_user:
    file: ./psql_user.txt
  psql_password:
    file: ./psql_password.txt
